---
exclude_paths:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - languages/
  - js/vendor/
  - vendor/
  - ".sass-cache/"
  - "hooks/post-merge"
  - "js/script.js"
  - "markdown.rb"
  - "phpunit.xml"
  - "phpunit.xml.dist"
  - "**/*.min.css"
  - "**/*.min.js"
  - "**.css"
  - "**.css.map"
  - "**.gif"
  - "**.jpg"
  - "**.png"
  - "**.svg"

prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.scss-lint-r-2.x.yml"
      path: ".scss-lint.yml"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintrc"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintignore"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.mdlrc"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/markdown.rb"
    - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/phpcs-themes.xml"
      path: "phpcs.xml"

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - php
    exclude_paths:
      - Gruntfile.js
  eslint:
    enabled: false
    channel: eslint-5
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: "phpcs.xml"
      ignore_warnings: false
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: codesize,naming,unusedcode
  stylelint:
    enabled: true
    config:
      file_extensions: scss
ratings:
  paths:
    - "**.md"
    - "**.inc"
    - "**.js"
    - "**.json"
    - "**.php"
    - "**.scss"
