name: Github Label Importer

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        uses: julbme/gh-action-manage-label@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from: https://raw.githubusercontent.com/bu-ist/responsive-child-starter/labels-patch-1/.github/labels.yml
          skip-delete: true
          exclude: |
            help*
            *issue
